version: '2'
networks:
  internal:
    name: internal
    external: true
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - 8081:80
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db1
    volumes:
      - ./dev:/var/www/html
    networks:
      - internal
    depends_on:
      - db
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    environment:
      DB_HOST: db
      DB_USER: user
      B_PASSWORD: password
      DB_NAME: db1
    volumes:
      - ./prod:/var/www/html
    networks:
      - internal
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal
